extends: default

rules:
  # Line length
  line-length:
    max: 120
    level: warning

  # Comments
  comments:
    min-spaces-from-content: 1

  # Indentation
  indentation:
    spaces: 2

  # Truthy values
  truthy:
    allowed-values: ["true", "false", "yes", "no"]

  # Document start
  document-start: disable

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

ignore: |
  .github/
  node_modules/
  target/
  .git/
  *.jar
  *.class
